#!/usr/bin/env python

import os

roots = [ 'yices_obj', 'libpoly_obj' ]

objs = []

for root in roots:
    for subdir, dirs, files in os.walk(root):
        for file in files:
            objs.append('"{0}"'.format(str(os.path.join(subdir, file))))


manifest_template = """
"modules" : [{0}]
, "binary"  : "occam_yices"
, "libs"    : []
, "native-libs" : ["-lgmp"]
, "search"  : ["/usr/lib", "/usr/local/lib", "/usr/lib/x86_64-linux-gnu/"]
, "name"    : "occam_yices"
"""

manifest =  '{ ' + manifest_template.format(", ".join(objs)) + ' }'


with open('yices.manifest', 'w') as output:
            output.write(manifest)
