#!/usr/bin/env python

import os

roots = [ 'yices_obj', 'gmp_obj' ]

objs = []

for root in roots:
    for subdir, dirs, files in os.walk(root):
        for file in files:
            (root, ext) = os.path.splitext(file)
            if ext == '.bc':
                objs.append('"{0}"'.format(str(os.path.join(subdir, file))))


manifest_template = """
"modules" : [{0}]
, "binary"  : "yices_smt2_gmp_previrt"
, "libs"    : []
, "native-libs" : []
, "search"  : ["/usr/lib", "/usr/local/lib", "/usr/lib/x86_64-linux-gnu/"]
, "name"    : "yices_smt2_gmp_previrt"
"""

manifest =  '{ ' + manifest_template.format(", ".join(objs)) + ' }'


with open('yices.manifest', 'w') as output:
            output.write(manifest)
