


all:
	@echo "Just type ./build.sh; this is here just for 'make clean'"



clean:
	rm -f *.ll *.bc .*.bc .*.o *.s nweb nweb-base nweb.manifest nweb*.o index.html* 
	rm -rf previrt slash index.html* root/nweb.log

