export HOME=/home/vagrant

export REPOS=${HOME}/Repositories

#### llvm 

export LLVM_HOME=/usr/lib/llvm-3.5/

######## whole-program-llvm configuration #############

export LLVM_COMPILER=clang

export WLLVM_OUTPUT=WARNING

########  Occam configuration ################

export OCCAM_SRC=${REPOS}/OCCAM/occam

export OCCAM_HOME=${HOME}/occam

export OCCAM_LOGFILE=${HOME}/.occam.log

export LLVM_HOME=/usr

export CC=clang

export CXX=clang++

#things like coreutils don't like clang-cpp-3.5
export CPP="clang -E"






