clean:
	$(MAKE) -C inter-1 clean
	$(MAKE) -C inter-2 clean
	$(MAKE) -C inter-3 clean
	$(MAKE) -C inter-4 clean
	$(MAKE) -C intra-1 clean
	$(MAKE) -C intra-2 clean
	$(MAKE) -C intra-3 clean
	$(MAKE) -C intra-4 clean
	$(MAKE) -C intra-5 clean
	$(MAKE) -C ffi-callback clean
	rm -rf config-prime-bitcode
