export HOME=/home/vagrant

export REPOS=${HOME}/Repositories

####  llvm

export LLVM_HOME=/usr/lib/llvm-3.5/

######## whole-program-llvm configuration #############

export WLLVM_HOME=${REPOS}/whole-program-llvm

export LLVM_COMPILER=clang

export WLLVM_OUTPUT=WARNING

########  Occam configuration ################

export OCCAM_SRC=${REPOS}/OCCAM/occam

export OCCAM_HOME=${HOME}/occam

export OCCAM_LOGFILE=${HOME}/.occam.log

export LLVM_HOME=/usr

export CC=${LLVM_CC_NAME}

export CXX=${LLVM_CXX_NAME}

#things like coreutils don't like clang-cpp-3.5
export CPP="${LLVM_CC_NAME} -E"

export PATH=${WLLVM_HOME}:${PATH}

alias occam=${OCCAM_HOME}/bin/occam






