clean:
	make -C simple clean
	make -C tree clean
	make -C multiple clean
	make -C modules clean
	make -C libcallmain clean
	make -C hello clean
	make -C globals clean
	make -C funcs/1 clean
	make -C funcs/2 clean
	make -C funcs/3 clean
	make -C funcs/4 clean
	make -C funcs/5 clean
	make -C funcs/6 clean
	make -C argv clean
	make -C fib clean
	make -C fiblib clean
	rm -Rf Output

