######## whole-program-llvm configuration #############

export WLLVM_HOME=${REPOS}/whole-program-llvm
export LLVM_COMPILER=clang
export WLLVM_OUTPUT=WARNING

########  Occam configuration ################

export LLVM_HOME=/usr/lib/llvm-3.5/
export CC=clang
export CXX=clang++
export CPP='clang -E'
export PATH=${WLLVM_HOME}:${PATH}

alias occam=${OCCAM_HOME}/bin/occam
