########  Occam configuration ################

export LLVM_HOME=/usr/lib/llvm-3.5/
export CC=clang
export CXX=clang++
export CPP='clang -E'
export PATH=${WLLVM_HOME}:${PATH}

alias occam=${OCCAM_HOME}/bin/occam
