
# /usr/lib/python2.7/occam/ply/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'W\xb6\x95\xac\xa6\x98\xd5\x990)\xd9\xcc\xa0jc\xfc'
    
_lr_action_items = {'THEN':([62,],[66,]),'RETURN':([14,24,46,66,69,],[18,18,18,18,18,]),'HOOK':([0,1,18,19,20,23,28,29,31,32,33,45,47,61,67,68,70,],[3,3,-31,-10,-11,-9,-21,-30,-32,-18,-20,-17,-19,-33,-34,-35,-36,]),'REL':([41,],[48,]),'VAR':([9,15,18,22,28,32,33,34,35,42,44,47,58,59,],[12,12,33,33,-21,-18,-20,41,33,33,33,-19,33,33,]),'MVAR':([18,22,28,32,33,35,42,44,47,58,59,],[28,28,-21,-18,-20,28,28,28,-19,28,28,]),')':([9,11,12,15,25,28,32,33,44,47,51,53,54,55,57,58,59,63,64,65,],[-12,14,-13,-12,-14,-21,-18,-20,-27,-19,-28,61,-25,-24,62,-27,-27,67,-29,-26,]),'(':([5,6,7,21,27,28,32,33,36,47,50,],[-3,9,-4,34,-8,-21,-18,-20,44,-19,58,]),',':([12,16,28,32,33,47,51,54,55,65,],[15,26,-21,-18,-20,-19,59,-25,-24,-26,]),'RE':([3,],[5,]),'FORWARD':([14,24,46,66,69,],[19,19,19,19,19,]),'EXCLUDE':([8,],[10,]),';':([18,19,20,28,29,31,32,33,38,45,47,61,67,68,70,],[-31,-10,-11,-21,-30,-32,-18,-20,46,-17,-19,-33,-34,-35,-36,]),':':([5,30,52,],[8,40,40,]),'$end':([1,2,4,18,19,20,23,28,29,31,32,33,45,47,61,67,68,70,],[-1,0,-2,-31,-10,-11,-9,-21,-30,-32,-18,-20,-17,-19,-33,-34,-35,-36,]),'UNDEF':([18,],[31,]),'ELSE':([18,19,20,28,29,31,32,33,45,47,61,67,68,70,],[-31,-10,-11,-21,-30,-32,-18,-20,-17,-19,-33,-34,69,-36,]),'STR':([13,18,22,26,28,32,33,35,42,44,47,58,59,],[16,32,32,16,-21,-18,-20,32,32,32,-19,32,32,]),'ELIPSIS':([44,52,58,59,],[54,60,54,54,]),'FAIL':([14,24,46,66,69,],[20,20,20,20,20,]),'[':([10,22,],[13,35,]),']':([13,16,17,26,28,32,33,39,42,43,47,49,],[-5,-6,27,-5,-21,-18,-20,-7,-22,50,-19,-23,]),'IF':([14,24,46,66,69,],[21,21,21,21,21,]),'INT':([18,22,28,32,33,35,40,42,44,47,48,58,59,60,],[30,30,-21,-18,-20,30,47,30,52,-19,57,52,52,65,]),'CALL':([14,24,46,66,69,],[22,22,22,22,22,]),'{':([14,24,46,66,69,],[24,24,24,24,24,]),'}':([18,19,20,28,29,31,32,33,37,38,45,47,56,61,67,68,70,],[-31,-10,-11,-21,-30,-32,-18,-20,45,-16,-17,-19,-15,-33,-34,-35,-36,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prim_exprs':([44,58,59,],[51,51,51,]),'action_seq':([24,46,],[37,56,]),'pattern':([3,],[6,]),'args':([9,15,],[11,25,]),'watch':([0,1,],[1,1,]),'watches':([0,1,],[2,4,]),'strings':([13,26,],[17,39,]),'prim_exprs_list':([44,58,59,],[53,63,64,]),'action':([14,24,46,66,69,],[23,38,38,68,70,]),'prim_expr':([18,22,35,42,44,58,59,],[29,36,42,42,55,55,55,]),'match_pred':([5,],[7,]),'prim_expr_list':([35,42,],[43,49,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> watches","S'",1,None,None,None),
  ('watches -> watch','watches',1,'p_watches','/usr/lib/python2.7/occam/watchparse2.py',86),
  ('watches -> watch watches','watches',2,'p_watches','/usr/lib/python2.7/occam/watchparse2.py',87),
  ('pattern -> RE','pattern',1,'p_pattern','/usr/lib/python2.7/occam/watchparse2.py',96),
  ('pattern -> RE match_pred','pattern',2,'p_pattern','/usr/lib/python2.7/occam/watchparse2.py',97),
  ('strings -> <empty>','strings',0,'p_strings','/usr/lib/python2.7/occam/watchparse2.py',106),
  ('strings -> STR','strings',1,'p_strings','/usr/lib/python2.7/occam/watchparse2.py',107),
  ('strings -> STR , strings','strings',3,'p_strings','/usr/lib/python2.7/occam/watchparse2.py',108),
  ('match_pred -> : EXCLUDE [ strings ]','match_pred',5,'p_match_pred','/usr/lib/python2.7/occam/watchparse2.py',121),
  ('watch -> HOOK pattern ( args ) action','watch',6,'p_watch','/usr/lib/python2.7/occam/watchparse2.py',128),
  ('action -> FORWARD','action',1,'p_action_forward','/usr/lib/python2.7/occam/watchparse2.py',132),
  ('action -> FAIL','action',1,'p_action_fail','/usr/lib/python2.7/occam/watchparse2.py',137),
  ('args -> <empty>','args',0,'p_args','/usr/lib/python2.7/occam/watchparse2.py',143),
  ('args -> VAR','args',1,'p_args','/usr/lib/python2.7/occam/watchparse2.py',144),
  ('args -> VAR , args','args',3,'p_args','/usr/lib/python2.7/occam/watchparse2.py',145),
  ('action_seq -> action ; action_seq','action_seq',3,'p_action_seq','/usr/lib/python2.7/occam/watchparse2.py',156),
  ('action_seq -> action','action_seq',1,'p_action_seq','/usr/lib/python2.7/occam/watchparse2.py',157),
  ('action -> { action_seq }','action',3,'p_action_block','/usr/lib/python2.7/occam/watchparse2.py',167),
  ('prim_expr -> STR','prim_expr',1,'p_prim_expr_str','/usr/lib/python2.7/occam/watchparse2.py',177),
  ('prim_expr -> INT : INT','prim_expr',3,'p_prim_expr_int','/usr/lib/python2.7/occam/watchparse2.py',181),
  ('prim_expr -> VAR','prim_expr',1,'p_prim_expr_var','/usr/lib/python2.7/occam/watchparse2.py',187),
  ('prim_expr -> MVAR','prim_expr',1,'p_prim_expr_mvar','/usr/lib/python2.7/occam/watchparse2.py',190),
  ('prim_expr_list -> prim_expr','prim_expr_list',1,'p_prim_expr_list','/usr/lib/python2.7/occam/watchparse2.py',195),
  ('prim_expr_list -> prim_expr prim_expr_list','prim_expr_list',2,'p_prim_expr_list','/usr/lib/python2.7/occam/watchparse2.py',196),
  ('prim_exprs -> prim_expr','prim_exprs',1,'p_prim_exprs_prim_expr','/usr/lib/python2.7/occam/watchparse2.py',208),
  ('prim_exprs -> ELIPSIS','prim_exprs',1,'p_prim_exprs','/usr/lib/python2.7/occam/watchparse2.py',214),
  ('prim_exprs -> INT ELIPSIS INT','prim_exprs',3,'p_prim_exprs','/usr/lib/python2.7/occam/watchparse2.py',215),
  ('prim_exprs_list -> <empty>','prim_exprs_list',0,'p_prim_exprs_list','/usr/lib/python2.7/occam/watchparse2.py',225),
  ('prim_exprs_list -> prim_exprs','prim_exprs_list',1,'p_prim_exprs_list','/usr/lib/python2.7/occam/watchparse2.py',226),
  ('prim_exprs_list -> prim_exprs , prim_exprs_list','prim_exprs_list',3,'p_prim_exprs_list','/usr/lib/python2.7/occam/watchparse2.py',227),
  ('action -> RETURN prim_expr','action',2,'p_action_return1','/usr/lib/python2.7/occam/watchparse2.py',240),
  ('action -> RETURN','action',1,'p_action_return','/usr/lib/python2.7/occam/watchparse2.py',248),
  ('action -> RETURN UNDEF','action',2,'p_action_return','/usr/lib/python2.7/occam/watchparse2.py',249),
  ('action -> CALL prim_expr ( prim_exprs_list )','action',5,'p_action_call','/usr/lib/python2.7/occam/watchparse2.py',257),
  ('action -> CALL [ prim_expr_list ] ( prim_exprs_list )','action',7,'p_action_call','/usr/lib/python2.7/occam/watchparse2.py',258),
  ('action -> IF ( VAR REL INT ) THEN action','action',8,'p_action_if','/usr/lib/python2.7/occam/watchparse2.py',274),
  ('action -> IF ( VAR REL INT ) THEN action ELSE action','action',10,'p_action_if','/usr/lib/python2.7/occam/watchparse2.py',275),
]
