#!/usr/bin/env python

import sys
from llvmcpy.llvm import *


from code.callgraph import CallGraph

def main(args):
    if len(args) > 1:
        buffer = create_memory_buffer_with_contents_of_file(sys.argv[1])
        context = get_global_context()
        module = context.parse_ir(buffer)

        if module is None:
            return 0

        gname = sys.argv[1].replace('.', '_')



        callgraph = CallGraph(gname)

        for function in module.iter_functions():
            node = function.get_name()
            node_id = callgraph.addNode(node)
            if not function.is_declaration():
                calls = 0
                callees = set()
                for bb in function.iter_basic_blocks():
                    for instruction in bb.iter_instructions():
                        if instruction.is_a_call_inst():
                            callee = instruction.get_called().get_name()
                            calls += 1
                            if callee:
                                callees.add(callee)
                            #print(instruction.print_value_to_string())
                            #print(instruction.get_called().get_name())
                for callee in callees:
                    callgraph.addEdge(node_id, callee)

        #print(callgraph)
        print(callgraph.toDotString())

        return 0

    else:
        print("Usage: {0} <llvm bitcode or ir>\n".format(args[0]))
        return 1







if __name__ == '__main__':
    sys.exit(main(sys.argv))
