#https://github.com/aircrack-ng/aircrack-ng/archive/1.5.2.tar.gz

#sudo apt-get install build-essential autoconf automake libtool pkg-config libnl-3-dev libnl-genl-3-dev libssl-dev ethtool shtool rfkill zlib1g-dev libpcap-dev libsqlite3-dev libpcre3-dev libhwloc-dev libcmocka-dev


#autoreconf -i
#CC=gclang ./configure

