# Ian's Makefile -- point to the llvm-config of the version you want
# to build against (using the LLVM_CONFIG environment variable) and
# type make.
#
# Simple!
#
# but set the default if there is no environment version there...
ifeq ($(LLVM_CONFIG),)
	LLVM_CONFIG=llvm-config
endif

# BD: made all things dependent on LLVM_HOME

LLVM_CFG = $(LLVM_HOME)/bin/$(LLVM_CONFIG)

LLVM_INCLUDE = $(shell ${LLVM_CFG} --includedir)

CXX_FLAGS += $(shell  ${LLVM_CFG} --cxxflags) -I${LLVM_INCLUDE}


############################################
## Choose one of these three build types:
############################################
CXX_RELEASE_FLAGS += -O3 -DNDEBUG
CXX_RELWITHDEBINFO_FLAGS += -O2 -g -DNDEBUG
CXX_DEBUG_FLAGS += -g
############################################
CXX_FLAGS += ${CXX_RELEASE_FLAGS}
#CXX_FLAGS += ${CXX_DEBUG_FLAGS}

OS   =  $(shell uname)
